class TcSamMacro(object):
    Resources = "Resources"
    Type = "Type"
    Properties = "Properties"
    CodeUri = "CodeUri"
    Desc = "Description"
    Envi = "Environment"
    Vari = "Variables"
    Handler = "Handler"
    MemSize = "MemorySize"
    Runtime = "Runtime"
    Timeout = "Timeout"
    Events = "Events"
    Globals = "Globals"
    Function = "Function"
